apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-tenant
  namespace: minio
spec:
  values:
    tenant:
      name: myminio
      configSecret:
        name: myminio-env-configuration
        accessKey: minio
        secretKey: minio123
      pools:
        - servers: 1
          name: pool-0
          volumesPerServer: 1
          size: 10Gi