apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: trino
  namespace: trino
spec:
  interval: 5m
  chart:
    spec:
      chart: trino
      sourceRef:
        kind: HelmRepository
        name: trino
        namespace: flux-system
      version: "0.12.0"
  install:
    createNamespace: true
  values:
    server:
      config:
        query:
          max-memory: "4GiB"
    coordinator:
      replicas: 1
    worker:
      replicas: 2
