apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: minio
spec:
  interval: 5m
  chart:
    spec:
      chart: minio/minio-operator
      sourceRef:
        kind: HelmRepository
        name: trino
        namespace: flux-system
  install:
    createNamespace: true
  values: {}